[features]
seeds = false
skip-lint = false

[programs.localnet]
promise = "EPwTUQEDoSREqyG9kp4rn2NtxkumDoMGdGnACv6s8J3A"

[programs.devnet]
promise = "DB5HAVRLPUYfUcAKK8A57JAihfZvcT3q17wNESfVb4AP"

[programs.testnet]
promise = "EPwTUQEDoSREqyG9kp4rn2NtxkumDoMGdGnACv6s8J3A"

# [programs.mainnet]
# promise = "TODO"

[registry]
url = "https://api.apr.dev"

[provider]
cluster = "localnet"
wallet = "/Users/justinguedes/.config/solana/id.json"

[scripts]
test = "yarn run ts-mocha -p ./tsconfig.json -t 1000000 ./tests/**/*.ts"

[workspace]
types = "sdk/src/idl/"
members = [
  "program",
]
